id: P24F3723F
initial_creation_type: input
source_metadata:
  Title: Suhṛllekhaḥ
  Editor: Tendzin, Padma
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: India
  Year: '2002'
  Suhṛllekhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:37:34.446555'
last_modified_at: '2022-03-08T16:37:34.446565'
